[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
priority=10
autostart=true
autorestart=true

[program:nginx]
command=/bin/sh -c "envsubst '$PORT' < /etc/nginx/templates/default.conf.template > /etc/nginx/sites-available/default && nginx -g 'daemon off;'"
priority=20
autostart=true
autorestart=true